name: "WebJWT"
version: "1.2.7"
slug: "webjwt"
description: "API de autenticación JWT"
arch:
  - amd64
  - aarch64
ports:
  8181/tcp: 8181
startup: application
boot: auto
options:
  JwtKey: ""
  JwtUsername: ""
  JwtPassword: ""
schema:
  JwtKey: str
  JwtUsername: str
  JwtPassword: str