name: "WebJWT"
version: "1.2.6"
slug: "webjwt"
description: "API de autenticación JWT"
arch:
  - amd64
  - aarch64
ports:
  8181/tcp: 8181
startup: application
boot: auto
options:
  JwtKey: ""
  JwtUsername: ""
  JwtPassword: ""
schema:
  JwtKey: str
  JwtUsername: str
  JwtPassword: str
environment:
  JwtKey: "1234567890123567890123456789011234567890"
  JwtUsername: "willytpfw"
  JwtPassword: "Dejamelo1"
